os: linux
dist: trusty
sudo: required
language: python

env:
  - UNITTEST_NYAWC_SITE=1

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7-dev

install:
  - sudo apt-get install -y apache2
  - sudo apt-get install -y php5-common libapache2-mod-php5
  - sudo service apache2 restart
  - sudo rm -r /var/www/html/*
  - sudo mv -T test/site /var/www/html
  - sudo chown -R www-data:www-data /var/www
  - pip install --upgrade setuptools
  - pip install -r requirements.txt

script:
  - python -m unittest discover
